import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

const GATEWAY_URL = "https://connector-gateway.lovable.dev/resend";

const schema = z.object({
  to: z.string().email(),
  subject: z.string().min(1).max(200),
  heading: z.string().min(1).max(200),
  intro: z.string().max(1000),
  rows: z.array(z.object({ label: z.string().max(80), value: z.string().max(200) })).max(20),
  footnote: z.string().max(500).optional(),
});

type Payload = z.infer<typeof schema>;

function renderEmail(p: Payload) {
  const rows = p.rows
    .map(
      (r) =>
        `<tr><td style="padding:8px 0;color:#6b7280;font-size:14px">${escape(r.label)}</td>` +
        `<td style="padding:8px 0;text-align:right;font-size:14px;color:#0f172a;font-weight:600">${escape(r.value)}</td></tr>`,
    )
    .join("");
  return `<!doctype html><html><body style="margin:0;background:#f6f7f5;font-family:Helvetica,Arial,sans-serif">
  <div style="max-width:560px;margin:0 auto;padding:32px 20px">
    <div style="font-size:20px;font-weight:700;color:#0b3b32;letter-spacing:-0.5px">Meridian</div>
    <div style="font-size:12px;color:#6b7280;margin-top:2px">African money in motion — demo environment</div>
    <div style="background:#ffffff;border-radius:14px;padding:24px;margin-top:18px;border:1px solid #e5e7eb">
      <h1 style="margin:0 0 10px;font-size:20px;color:#0f172a">${escape(p.heading)}</h1>
      <p style="margin:0 0 16px;font-size:14px;line-height:22px;color:#374151">${escape(p.intro)}</p>
      <table style="width:100%;border-collapse:collapse;border-top:1px solid #e5e7eb">${rows}</table>
      ${p.footnote ? `<p style="margin:18px 0 0;font-size:12px;line-height:18px;color:#6b7280">${escape(p.footnote)}</p>` : ""}
    </div>
    <p style="font-size:11px;color:#9ca3af;margin-top:16px;line-height:17px">
      Meridian is a product of Appify Softwares Limited (appify.co.ke). Meridian is a technology platform only and
      does not hold or handle client funds. This message was generated by a product demo — no money moved.
    </p>
  </div></body></html>`;
}

function escape(s: string) {
  return s.replace(/[&<>"']/g, (c) =>
    c === "&" ? "&amp;" : c === "<" ? "&lt;" : c === ">" ? "&gt;" : c === '"' ? "&quot;" : "&#39;",
  );
}

export const sendNotification = createServerFn({ method: "POST" })
  .inputValidator((data: unknown) => schema.parse(data))
  .handler(async ({ data }) => {
    const lovableKey = process.env["LOVABLE_API_KEY"];
    const resendKey = process.env["RESEND_API_KEY"];
    if (!lovableKey || !resendKey) {
      return { sent: false, reason: "email_not_configured" as const };
    }

    const response = await fetch(`${GATEWAY_URL}/emails`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${lovableKey}`,
        "X-Connection-Api-Key": resendKey,
      },
      body: JSON.stringify({
        from: "Meridian Demo <onboarding@resend.dev>",
        to: [data.to],
        subject: data.subject,
        html: renderEmail(data),
      }),
    });

    if (!response.ok) {
      const body = await response.text();
      console.error(`Resend request failed [${response.status}]: ${body}`);
      return { sent: false, reason: "provider_error" as const, status: response.status };
    }

    return { sent: true as const };
  });
