// Email templates. Plain functions that return a subject, HTML and text.
// No I/O here, so they are unit tested.

import type { ContactInput, WaitlistInput } from "~/lib/schemas";

export type Email = { subject: string; html: string; text: string };
type Row = { label: string; value: string };

type Layout = {
  subject: string;
  heading: string;
  intro: string;
  rows: Row[];
  footnote?: string;
  /** Demo emails say that no money moved. */
  demo?: boolean;
};

export function escapeHtml(s: string) {
  return s.replace(/[&<>"']/g, (c) =>
    c === "&" ? "&amp;" : c === "<" ? "&lt;" : c === ">" ? "&gt;" : c === '"' ? "&quot;" : "&#39;",
  );
}

export function render(p: Layout): Email {
  const rows = p.rows
    .map(
      (r) =>
        `<tr><td style="padding:8px 0;color:#6b7280;font-size:14px">${escapeHtml(r.label)}</td>` +
        `<td style="padding:8px 0;text-align:right;font-size:14px;color:#0f172a;font-weight:600">${escapeHtml(r.value)}</td></tr>`,
    )
    .join("");
  const legal =
    "Meridian is a product of Appify Softwares Limited (appify.co.ke). Meridian is a technology platform only and does not hold or handle client funds." +
    (p.demo ? " This message was generated by a product demo — no money moved." : "");
  const html = `<!doctype html><html><body style="margin:0;background:#f6f7f5;font-family:Helvetica,Arial,sans-serif">
  <div style="max-width:560px;margin:0 auto;padding:32px 20px">
    <div style="font-size:20px;font-weight:700;color:#0b3b32;letter-spacing:-0.5px">Meridian</div>
    <div style="font-size:12px;color:#6b7280;margin-top:2px">African money in motion${p.demo ? " — demo environment" : ""}</div>
    <div style="background:#ffffff;border-radius:14px;padding:24px;margin-top:18px;border:1px solid #e5e7eb">
      <h1 style="margin:0 0 10px;font-size:20px;color:#0f172a">${escapeHtml(p.heading)}</h1>
      <p style="margin:0 0 16px;font-size:14px;line-height:22px;color:#374151;white-space:pre-line">${escapeHtml(p.intro)}</p>
      <table style="width:100%;border-collapse:collapse;border-top:1px solid #e5e7eb">${rows}</table>
      ${p.footnote ? `<p style="margin:18px 0 0;font-size:12px;line-height:18px;color:#6b7280">${escapeHtml(p.footnote)}</p>` : ""}
    </div>
    <p style="font-size:11px;color:#9ca3af;margin-top:16px;line-height:17px">${escapeHtml(legal)}</p>
  </div></body></html>`;
  const text = [
    p.heading,
    "",
    p.intro,
    "",
    ...p.rows.map((r) => `${r.label}: ${r.value}`),
    ...(p.footnote ? ["", p.footnote] : []),
    "",
    legal,
  ].join("\n");
  return { subject: p.subject, html, text };
}

const dash = (v: string | undefined) => (v && v.trim() !== "" ? v : "—");

export function waitlistConfirmation(w: WaitlistInput): Email {
  return render({
    subject: "You're on the Meridian waitlist",
    heading: `Welcome aboard, ${w.contact_name.split(" ")[0] || "there"}`,
    intro:
      "Thanks for joining the Meridian waitlist. You'll be among the first businesses invited when we open early access, and we'll email you the moment the app is ready.",
    rows: [
      { label: "Business", value: w.business_name },
      { label: "Country", value: dash(w.country) },
      { label: "Monthly volume", value: dash(w.monthly_volume) },
    ],
    footnote:
      "Every waitlist signup helps us prioritise the corridors and payment methods we build first. Reply to this email any time to tell us more about your payment flows.",
  });
}

export function contactConfirmation(c: ContactInput): Email {
  return render({
    subject: "We received your message — Meridian",
    heading: "Thanks for reaching out",
    intro:
      "We've received your message and a member of the Meridian team at Appify Softwares will reply shortly. Here's a copy for your records.",
    rows: [
      { label: "Subject", value: c.subject?.trim() || "General enquiry" },
      { label: "Company", value: dash(c.company) },
      { label: "Message", value: c.message.slice(0, 180) },
    ],
  });
}

export type Lead =
  { kind: "waitlist"; data: WaitlistInput } | { kind: "contact"; data: ContactInput };

/** Internal alert to Appify for every new waitlist signup or contact message (M-06). */
export function leadAlert(lead: Lead): Email {
  if (lead.kind === "waitlist") {
    const w = lead.data;
    return render({
      subject: `New waitlist signup: ${w.business_name}`,
      heading: "New waitlist signup",
      intro: `${w.contact_name} from ${w.business_name} joined the waitlist.`,
      rows: [
        { label: "Business", value: w.business_name },
        { label: "Name", value: w.contact_name },
        { label: "Email", value: w.email },
        { label: "Country", value: dash(w.country) },
        { label: "Monthly volume", value: dash(w.monthly_volume) },
        { label: "Who they pay", value: dash(w.pain_point) },
      ],
    });
  }
  const c = lead.data;
  return render({
    subject: `New contact message: ${c.subject?.trim() || "General enquiry"}`,
    heading: "New contact message",
    intro: c.message,
    rows: [
      { label: "Name", value: c.name },
      { label: "Email", value: c.email },
      { label: "Company", value: dash(c.company) },
      { label: "Subject", value: c.subject?.trim() || "General enquiry" },
    ],
  });
}

/** Sent to the admin when an email could not be delivered. */
export function emailFailureAlert(p: { to: string; subject: string; error: string }): Email {
  return render({
    subject: `Email failed: ${p.subject}`,
    heading: "An email could not be sent",
    intro: "Resend rejected or could not accept this email. It is logged in partner_calls.",
    rows: [
      { label: "To", value: p.to },
      { label: "Subject", value: p.subject },
      { label: "Error", value: p.error.slice(0, 300) },
    ],
  });
}

/** Demo receipts and notices. Same look, marked as demo. */
export function demoEmail(p: Omit<Layout, "demo">): Email {
  return render({ ...p, demo: true });
}

/* ------------------------------- collections ------------------------------ */
// Receipts and notices for the Payaza collection flow. Every one shows the
// business's invoice number (when given) and the Meridian reference.

export type CollectionFacts = {
  businessName: string;
  reference: string;
  attemptReference: string;
  invoiceNumber: string | null;
  memo: string | null;
  amount: string;
  totalCharged: string;
  totalFees: string;
  method: string;
  payerName: string | null;
  payerEmail: string | null;
  settledAt: string;
  payoutAccount: string;
  /** Sandbox runs say so on the receipt. */
  sandbox: boolean;
};

function refRows(f: CollectionFacts): Row[] {
  return [
    ...(f.invoiceNumber ? [{ label: "Invoice number", value: f.invoiceNumber }] : []),
    { label: "Meridian reference", value: f.reference },
    { label: "Payment reference", value: f.attemptReference },
  ];
}

const sandboxNote = (on: boolean) =>
  on ? "Sandbox payment through Payaza's test environment. No real money moved." : undefined;

export function payerReceipt(f: CollectionFacts): Email {
  const inv = f.invoiceNumber ? ` · ${f.invoiceNumber}` : "";
  return render({
    subject: `Receipt ${f.reference}${inv} — ${f.businessName}`,
    heading: "Payment received",
    intro: `${f.businessName} has received your payment of ${f.amount}. Thank you.`,
    rows: [
      ...refRows(f),
      { label: "Paid to", value: f.businessName },
      ...(f.memo ? [{ label: "For", value: f.memo }] : []),
      { label: "Amount", value: f.amount },
      { label: "Method", value: f.method },
      { label: "Fees", value: f.totalFees },
      { label: "You paid", value: f.totalCharged },
      { label: "Date", value: f.settledAt },
    ],
    footnote:
      sandboxNote(f.sandbox) ??
      "Keep this email as your receipt. Payments are processed by Payaza.",
  });
}

export function businessReceipt(f: CollectionFacts): Email {
  const inv = f.invoiceNumber ? ` for ${f.invoiceNumber}` : "";
  return render({
    subject: `You've been paid ${f.amount}${inv} (${f.reference})`,
    heading: "Payment settled",
    intro: `${f.payerName ?? "Your customer"} paid ${f.amount}. The full amount is on its way to ${f.payoutAccount}. The payer covered the fees.`,
    rows: [
      ...refRows(f),
      { label: "Paid by", value: f.payerName ?? "—" },
      ...(f.payerEmail ? [{ label: "Payer email", value: f.payerEmail }] : []),
      ...(f.memo ? [{ label: "For", value: f.memo }] : []),
      { label: "You receive", value: f.amount },
      { label: "Payer paid", value: f.totalCharged },
      { label: "Method", value: f.method },
      { label: "Paid out to", value: f.payoutAccount },
      { label: "Date", value: f.settledAt },
    ],
    footnote: sandboxNote(f.sandbox),
  });
}

export function paymentRequestEmail(p: {
  businessName: string;
  reference: string;
  invoiceNumber: string | null;
  memo: string | null;
  amount: string;
  url: string;
}): Email {
  const inv = p.invoiceNumber ? ` · ${p.invoiceNumber}` : "";
  return render({
    subject: `${p.businessName} requests ${p.amount}${inv}`,
    heading: `${p.businessName} sent you a payment request`,
    intro: `Open the link to pay by mobile money, bank transfer or card. Every fee is shown before you pay.\n${p.url}`,
    rows: [
      ...(p.invoiceNumber ? [{ label: "Invoice number", value: p.invoiceNumber }] : []),
      { label: "Meridian reference", value: p.reference },
      { label: "Amount", value: p.amount },
      ...(p.memo ? [{ label: "For", value: p.memo }] : []),
      { label: "Payment link", value: p.url },
    ],
  });
}

export function transactionHeldEmail(p: {
  businessName: string;
  reference: string;
  amount: string;
  reasons: string[];
  forAdmin: boolean;
}): Email {
  return render({
    subject: `${p.forAdmin ? "Review needed" : "Payment under review"}: ${p.reference}`,
    heading: p.forAdmin ? "A payment is on hold" : "Your payment is under review",
    intro: p.forAdmin
      ? `${p.amount} was collected for ${p.businessName} but the payout is on hold. Release or reject it in the admin.`
      : `${p.amount} was received against ${p.reference}. Before we pay it out we need to check something. We will email you within one business day.`,
    rows: [
      { label: "Meridian reference", value: p.reference },
      { label: "Amount", value: p.amount },
      { label: "Reason", value: p.reasons.join("; ") || "Under review" },
    ],
  });
}

export function transactionFailedEmail(p: {
  businessName: string;
  reference: string;
  amount: string;
  stage: "payment" | "payout";
  reason: string;
  forAdmin: boolean;
}): Email {
  const payout = p.stage === "payout";
  const intro = payout
    ? p.forAdmin
      ? `Payaza could not pay ${p.amount} to ${p.businessName}. The money is in Meridian's Payaza balance. Retry the payout or arrange a refund in the admin.`
      : `We received ${p.amount} for ${p.reference} but could not pay it to your account yet. We are on it and will email you when it is done.`
    : `The payment for ${p.reference} did not complete. No money moved.`;
  return render({
    subject: `${payout ? "Payout failed" : "Payment failed"}: ${p.reference}`,
    heading: payout ? "A payout did not go through" : "A payment did not go through",
    intro,
    rows: [
      { label: "Meridian reference", value: p.reference },
      { label: "Amount", value: p.amount },
      { label: "Reason", value: p.reason },
    ],
  });
}

export function flagAlertEmail(p: {
  rule: string;
  severity: string;
  businessName: string;
  reference: string | null;
  message: string;
}): Email {
  const on = p.reference ? ` on ${p.reference}` : "";
  return render({
    subject: `Flag (${p.severity}): ${p.rule}${on}`,
    heading: "A check raised a flag",
    intro: p.message,
    rows: [
      { label: "Rule", value: p.rule },
      { label: "Severity", value: p.severity },
      { label: "Business", value: p.businessName },
      ...(p.reference ? [{ label: "Reference", value: p.reference }] : []),
    ],
  });
}
