/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DemoCheckoutRouteImport } from './routes/demo.checkout'
import { Route as DemoRequestRouteImport } from './routes/demo.request'
import { Route as DemoSendRouteImport } from './routes/demo.send'
import { Route as PayReferenceRouteImport } from './routes/pay.$reference'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCheckoutRoute = DemoCheckoutRouteImport.update({
  id: '/demo/checkout',
  path: '/demo/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRequestRoute = DemoRequestRouteImport.update({
  id: '/demo/request',
  path: '/demo/request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSendRoute = DemoSendRouteImport.update({
  id: '/demo/send',
  path: '/demo/send',
  getParentRoute: () => rootRouteImport,
} as any)
const PayReferenceRoute = PayReferenceRouteImport.update({
  id: '/pay/$reference',
  path: '/pay/$reference',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/demo/checkout': typeof DemoCheckoutRoute
  '/demo/request': typeof DemoRequestRoute
  '/demo/send': typeof DemoSendRoute
  '/pay/$reference': typeof PayReferenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/demo/checkout': typeof DemoCheckoutRoute
  '/demo/request': typeof DemoRequestRoute
  '/demo/send': typeof DemoSendRoute
  '/pay/$reference': typeof PayReferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/demo/checkout': typeof DemoCheckoutRoute
  '/demo/request': typeof DemoRequestRoute
  '/demo/send': typeof DemoSendRoute
  '/pay/$reference': typeof PayReferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/demo/checkout'
    | '/demo/request'
    | '/demo/send'
    | '/pay/$reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/demo/checkout'
    | '/demo/request'
    | '/demo/send'
    | '/pay/$reference'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/demo/checkout'
    | '/demo/request'
    | '/demo/send'
    | '/pay/$reference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  DemoCheckoutRoute: typeof DemoCheckoutRoute
  DemoRequestRoute: typeof DemoRequestRoute
  DemoSendRoute: typeof DemoSendRoute
  PayReferenceRoute: typeof PayReferenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/checkout': {
      id: '/demo/checkout'
      path: '/demo/checkout'
      fullPath: '/demo/checkout'
      preLoaderRoute: typeof DemoCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/request': {
      id: '/demo/request'
      path: '/demo/request'
      fullPath: '/demo/request'
      preLoaderRoute: typeof DemoRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/send': {
      id: '/demo/send'
      path: '/demo/send'
      fullPath: '/demo/send'
      preLoaderRoute: typeof DemoSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$reference': {
      id: '/pay/$reference'
      path: '/pay/$reference'
      fullPath: '/pay/$reference'
      preLoaderRoute: typeof PayReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  DemoCheckoutRoute: DemoCheckoutRoute,
  DemoRequestRoute: DemoRequestRoute,
  DemoSendRoute: DemoSendRoute,
  PayReferenceRoute: PayReferenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
